# This is a basic workflow to help you get started with Actions

name: Test002

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - 'back/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run Only if path contains front       
        run: |
          echo "inside back/**"
          ls -l
