# This is a basic workflow to showcase the use of Reusable Workflows

name: Business Services Tests

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest
    env:
      CORE_ENVIRONMENT: ${{secrets.CONM_SECRET_KEY_BASE_DEV}}
    outputs:
      title: " ${{github.event_name}} ${{github.job}}"
      request: "Author: ${{github.actor}} Branch: ${{github.head_ref}} Target_Branch: ${{github.base_ref}} PR_ID: ${{github.run_number}}"
      result: "Result ${{job.status}}"

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        id: tests
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"blocks": [{"type": "section","text": {"type": "mrkdwn","text": "*${{github.event_name}}*"}},{"type": "section","block_id": "section789","fields": [{"type": "mrkdwn","text": "*Author*: ${{github.actor}}\n *PR_Branch*: ${{github.head_ref}}\n *Target_Branch*: ${{github.base_ref}}\n *PR_ID*: ${{github.run_number}}\n*Result*\n ${{job.status}}"}]}]}' \
          ${{secrets.SLACK_WEBHOOK}}
 # called:
 #   needs: do-it
  #  uses: suraj129/sample_githubrunner/.github/workflows/called.yml@main
   # with:
    #  title: "${{ needs.do-it.outputs.title }}"
     # request: "${{ needs.do-it.outputs.request }}"
      #result: "${{ needs.do-it.outputs.result }}"
