name: called	

on:
  workflow_call:
    inputs:
      msg:
        required: false
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: false
      registry_password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      - name: Print 
        run: echo "${{inputs.msg}}"

  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: |
        curl -d "text=${{inputs.msg}}" -d "channel=test-jenkins" -H "Authorization: Bearer xoxb-139213247411-2658721193203-L1fi71UkovBFBfcKttc1zyDl" -X POST https://slack.com/api/chat.postMessage

