name: called	

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      request: 
        type: string
      result:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      - name: Print 
        run: echo "${{inputs.msg}}"

  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "${{input.title}}\nRequest:${{input.request}}\nResult:${{input.result}}"
