name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: false
      registry_password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      - name: Print 
        run: echo "Hello,2"

  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello,3"
