# This is a basic workflow to showcase the use of Reusable Workflows

name: caller

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        id: tests
        run: echo Hello, world!

  called:
    needs: do-it
    uses: suraj129/sample_githubrunner/.github/workflows/called.yml@main
    with:
      msg: "${{ do-it.outputs }}"
      tag: "Failed"
