name: callee

on:
  workflow_call:
    inputs:
      channel:
        description: 'slack channel name'
        required: true
        default: 'test-jenkins'
        type: string
      token:
        description: 'token'
        required: false
        default: ''
        type: string

  workflow_dispatch:
    inputs:
      channel:
        description: 'slack channel name'
        required: true
        default: 'test-jenkins'
        type: string
      token:
        description: 'token'
        required: false
        default: ''
        type: string
jobs:
  callee:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use local my-action
        uses: ./.github/actions/notifySlack

