# This is a basic workflow to help you get started with Actions

name: CItests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main,master,develop ]
  #  types: [ labeled ]

  
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  pre_setUp:
    runs-on: self-hosted
  #  if: |
   #    ${{ github.event.label.name == 'env1' }} || ${{ github.event.label.name == 'env2' }} || ${{ github.event.label.name == 'env3' }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo ${tests} 
          echo $tests 
          echo $secrets.CONM_SECRET_KEY_BASE_DEV 01
          echo ${secrets.CONM_SECRET_KEY_BASE_DEV} 02

  rSpecTests:    
    runs-on: self-hosted
    needs: pre_setUp
    steps:
      - name: Run a one-line script
        run: export tests=Rspec


  frontendTests:    
    runs-on: self-hosted
    needs: pre_setUp
    steps:
      - name: Run a one-line script
        run: export tests=FrontEndTests


  trainingTests:
    runs-on: self-hosted
    needs: pre_setUp
    steps:
      - name: Run a one-line script
        run: export tests=trainingtests


  postAlways:
    runs-on: self-hosted
    needs: [ trainingTests,frontendTests,rSpecTests,pre_setUp ]
    if: always()
    steps:
      - name: Run a one-line script
        run: echo ${tests} $tests $CONM_SECRET_KEY_BASE_DEV ${CONM_SECRET_KEY_BASE_DEV}

