# This is a basic workflow to help you get started with Actions

name: CItests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    types: [ labeled ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  presetUp:
    runs-on: self-hosted
    if: |
       ${{ github.event.label.name == 'env1' }} || ${{ github.event.label.name == 'env2' }} || ${{ github.event.label.name == 'env3' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

  Rspec:    
    runs-on: self-hosted
    needs: presetUp
    steps:
      - name: Run a one-line script
        run: export tests=Rspec


  FrontEndTests:    
    runs-on: self-hosted
    needs: presetUp
    steps:
      - name: Run a one-line script
        run: export tests=FrontEndTests


  trainingtests:
    runs-on: self-hosted
    needs: presetUp
    steps:
      - name: Run a one-line script
        run: export tests=trainingtests


  postSlack:
    runs-on: self-hosted
    needs: [ trainingtests,FrontEndTests,Rspec,presetUp ]
    if: always()
    steps:
      - name: Run a one-line script
        run: echo ${tests} $tests
