# This is a basic workflow to help you get started with Actions

name: CITests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, develop ]
  	#types: [ labeled ]           
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'training/**'

#Pre-Setup ENVIRONMENT
env:
  CORE_ENVIRONMENT: ${secrets.CORE_ENVIRONMENT}
  USER_CREDENTIALS: ${secrets.USER_CREDENTIALS}
  CONM_SECRET_KEY_BASE_DEV: ${secrets.CONM_SECRET_KEY_BASE_DEV}
  CONM_SECRET_KEY_BASE_TEST: ${secrets.CONM_SECRET_KEY_BASE_TEST}
  TRUSTED_COMPONENT_ID: ${secrets.TRUSTED_COMPONENT_ID}
  TRUSTED_COMPONENT_KEY: ${secrets.TRUSTED_COMPONENT_KEY}
  CONM_BUCKET_DEV: ${secrets.CONM_BUCKET_DEV}
  CONM_BUCKET_TEST: ${secrets.CONM_BUCKET_TEST}    
	  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    	         	   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
	  		  	
      - name: Create environment file
        run: |
          echo "" > .env
          echo "CONM_SECRET_KEY_BASE_DEV=${secrets.CONM_SECRET_KEY_BASE_DEV}" >> .env
          echo "CONM_SECRET_KEY_BASE_TEST=${secrets.CONM_SECRET_KEY_BASE_TEST}" >> .env
          echo "TRUSTED_COMPONENT_ID=${secrets.TRUSTED_COMPONENT_ID}" >> .env
          echo "TRUSTED_COMPONENT_KEY=${secrets.TRUSTED_COMPONENT_KEY}" >> .env
          echo "CONM_BUCKET_DEV=${secrets.CONM_BUCKET_DEV}" >> .env
          echo "CONM_BUCKET_TEST=${secrets.CONM_BUCKET_TEST}" >> .env
		  
      - name: Run Frontend Tests
        if: ${{ github.event.paths == 'frontend/**' }}
        run: |
          echo "Frontend"
		
      - name: Run Compose Build
        if: ${{ github.event.path == 'backend/**' }}
        run: |
          echo "backend"
		  
      - name: Run Rspec Tests	
        if: ${{ github.event.paths == 'backend/**' }}
        run: |
          echo "backend-2"
          
      - name: Run Training Tests	
        if: ${{ github.event.paths == 'training/**' }}
        run: |
          echo "training"
